### ISSUE TITLE
box joints

### ISSUE THREAD

**Issue by nclemmons** [marvingreenberg/SOjoinery#6] opened 2019-01-30 14:55 UTC
Typically box joints will be thru cut.  The SVG you are generating still has a gutter for both pieces.  Shouldn't the face piece be a thru cut with no gutter.  

I'm assuming you are cutting the box joint with the wood held in a vertical workstation type of setup.

I usually cut them with several pieces held at once - so four 1/2" pieces for example.  I can increase the material thickness to 2", but the gutter is still there.

Make sense?  Seems like the cutter might be either 0 or maybe 1/8" assuming I am using a spoil board on each side of the piece.

neil

**Comment by marvingreenberg** [comment] 2019-01-30 15:31
This is a duplicate of #2, or at least related, I think.  I also think I need to make a ShaperHub project - these joints are different than traditional box joints - they're "SO BoxJoints"  I think I need to explain my thinking about this (but I haven't figured out how to generate documentation panels yet).  If all you want is a "traditional" box joint you can just set material size to, say 4, and you'll have plenty of the pattern to cut through 4 boards.  And then, just like with "bulbous" I think you'll want the option for "symmetric" and "asymmetric" variants.  All of which should be _relatively_ simple to fix.

**Comment by marvingreenberg** [comment] 2019-01-30 15:38
BTW, neither image has a gutter.  The second "edge" svg is a pocket cut, that extends a multiple of a typical grid to allow you to pocket. The blue annotation line indicates the board edge for alignment and there is no space between the pin end and that line.  As I said, I need to explain better what I am thinking, and for many folks you really would never make box joints the way I am imagining, and would use your approach.  I need to (a) explain my way, and (b) directly support your way since it is much more practical.

**Comment by marvingreenberg** [comment] 2019-02-01 15:23
I'm closing this - the existing generated images can be used as desired.

**Closed by marvingreenberg** 2019-02-01 15:23 UTC
Labels: bug:joinery
